import type { BaseEntityMetadata } from './types.js'

export const baseEntityMetadata: readonly BaseEntityMetadata[] = [
	{ id: 'pinhole', kind: 'world', family: 'cosmic', capabilities: ['indestructible', 'singleton', 'soulProducer'] },
	{ id: 'strange', kind: 'world', family: 'monoliths', capabilities: ['clickable', 'indestructible', 'multiCell', 'soulProducer'] },
	{ id: 'strange1', kind: 'world', family: 'monoliths', capabilities: ['clickable', 'indestructible', 'singleton', 'multiCell'] },
	{ id: 'strange2', kind: 'world', family: 'monoliths', capabilities: ['clickable', 'indestructible', 'singleton', 'soulProducer'] },
	{ id: 'strange3', kind: 'world', family: 'monoliths', capabilities: ['clickable', 'indestructible', 'singleton', 'soulProducer'] },
	{ id: 'voidsculpture', kind: 'world', family: 'cosmic', capabilities: ['clickable', 'indestructible', 'singleton', 'soulProducer'] },
	{ id: 'gradient', kind: 'machine', family: 'channels', capabilities: ['extractor', 'relocatable', 'soulProducer'] },
	{ id: 'chasm', kind: 'world', family: 'cosmic', capabilities: ['singleton', 'soulProducer'] },
	{ id: 'conductor', kind: 'machine', family: 'industrial', capabilities: ['relocatable', 'soulProducer'] },
	{ id: 'vault', kind: 'machine', family: 'storage', capabilities: ['storage', 'relocatable', 'soulProducer'] },
	{ id: 'pump', kind: 'machine', family: 'pumps', capabilities: ['extractor', 'soulProducer'] },
	{ id: 'pump2', kind: 'machine', family: 'pumps', capabilities: ['extractor', 'soulProducer'] },
	{ id: 'cube', kind: 'entity', family: 'minerals', capabilities: ['clickable'] },
	{ id: 'destabilizer', kind: 'machine', family: 'destabilizers', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'destabilizer2', kind: 'machine', family: 'destabilizers', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'destabilizer2a', kind: 'machine', family: 'destabilizers', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'injector', kind: 'machine', family: 'destabilizers', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'doublechannel', kind: 'machine', family: 'channels', capabilities: ['relocatable', 'soulProducer'] },
	{ id: 'doublechannel2', kind: 'machine', family: 'channels', capabilities: ['relocatable', 'soulProducer'] },
	{ id: 'valve', kind: 'machine', family: 'channels', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'auxpump', kind: 'machine', family: 'channels', capabilities: ['fuelConsumer', 'auxSpeedBoost', 'relocatable', 'soulProducer'] },
	{ id: 'auxpump2', kind: 'machine', family: 'channels', capabilities: ['fuelConsumer', 'auxSpeedBoost', 'relocatable', 'soulProducer'] },
	{ id: 'entropic', kind: 'machine', family: 'entropics', capabilities: ['fuelConsumer', 'continuousPowerProvider', 'relocatable', 'soulProducer'] },
	{ id: 'entropic2', kind: 'machine', family: 'entropics', capabilities: ['fuelConsumer', 'continuousPowerProvider', 'relocatable', 'soulProducer'] },
	{ id: 'entropic2a', kind: 'machine', family: 'entropics', capabilities: ['fuelConsumer', 'instantPowerProvider', 'relocatable', 'soulProducer'] },
	{ id: 'entropic3', kind: 'machine', family: 'entropics', capabilities: ['fuelConsumer', 'continuousPowerProvider', 'annihilator', 'relocatable', 'soulProducer'] },
	{ id: 'converter32', kind: 'machine', family: 'converters', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'converter13', kind: 'machine', family: 'converters', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'converter41', kind: 'machine', family: 'converters', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'converter76', kind: 'machine', family: 'converters', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'converter64', kind: 'machine', family: 'converters', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'reflector', kind: 'machine', family: 'converters', capabilities: ['relocatable', 'soulProducer'] },
	{ id: 'preheater', kind: 'machine', family: 'converters', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'mega1', kind: 'machine', family: 'megas', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'mega1a', kind: 'machine', family: 'megas', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'mega1b', kind: 'machine', family: 'megas', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'mega2', kind: 'machine', family: 'megas', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'mega3', kind: 'machine', family: 'megas', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'eye', kind: 'entity', family: 'anomalies', capabilities: ['singleton', 'soulProducer'] },
	{ id: 'cookie', kind: 'world', family: 'anomalies', capabilities: ['clickable', 'soulProducer'] },
	{ id: 'silo', kind: 'machine', family: 'storage', capabilities: ['storage', 'fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'silo2', kind: 'machine', family: 'storage', capabilities: ['storage', 'fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'vessel', kind: 'machine', family: 'storage', capabilities: ['storage', 'fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'vessel2', kind: 'machine', family: 'storage', capabilities: ['storage', 'fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'consumer', kind: 'machine', family: 'industrial', capabilities: ['fuelConsumer', 'relocatable', 'soulProducer'] },
	{ id: 'hollow', kind: 'world', family: 'botanicals', capabilities: ['clickable'] },
	{ id: 'generaldecay', kind: 'world', family: 'anomalies', capabilities: ['singleton', 'soulProducer'] },
	{ id: 'waypoint', kind: 'world', family: 'anomalies', capabilities: ['clickable', 'soulProducer'] },
	{ id: 'annihilator', kind: 'machine', family: 'industrial', capabilities: ['fuelConsumer', 'annihilator', 'relocatable', 'soulProducer'] },
	{ id: 'flower', kind: 'world', family: 'botanicals', capabilities: ['soulProducer'] },
	{ id: 'fruit', kind: 'world', family: 'botanicals', capabilities: ['clickable'] },
	{ id: 'clicker1', kind: 'machine', family: 'clickers', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'clicker2', kind: 'machine', family: 'clickers', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'clicker3', kind: 'machine', family: 'clickers', capabilities: ['singleton', 'relocatable', 'soulProducer'] },
	{ id: 'stabilizer', kind: 'machine', family: 'stabilizers', capabilities: ['relocatable', 'soulProducer'] },
	{ id: 'stabilizer2', kind: 'machine', family: 'stabilizers', capabilities: ['relocatable', 'soulProducer'] },
	{ id: 'stabilizer3', kind: 'machine', family: 'stabilizers', capabilities: ['relocatable', 'soulProducer'] },
	{ id: 'surge', kind: 'entity', family: 'anomalies', capabilities: ['soulProducer'] },
]
